---
- name: format disk
  become: true
  hosts: localhost
  tasks:
    - name: get disk structure
      become: true
      command: fdisk -l
      register: get_disk
    - name: pour la mise au point
      debug:
        msg: " device : {{ get_disk.stdout | get_device }}"
    - name: prochaine
      vars:
        device: "{{ get_disk.stdout | get_device }}"
      shell: echo {{ item }}
      when: device is defined 
      loop: "{{ device }}" 
    - name: format disk 
      vars:
        device: "{{ get_disk.stdout | get_device }}"
      filesystem:
        fstype: ext4
        dev: "{{ item }}"
      when: device is defined 
      loop: "{{ device }}"
